### ISSUE TITLE
Unable to install on OSX Mojave

### ISSUE THREAD

**Issue by eddielong** [evangoer/scrape-markdown#2]
NPM: 6.4.1
Platform: OSX 10.14.1

Callstack:

```
npm install scrape-markdown
npm WARN deprecated html-md@3.0.2: Package has been moved to Europa: https://www.npmjs.com/package/europa

> contextify@0.1.15 install /Volumes/Code/developer-site/node_modules/contextify
> node-gyp rebuild

  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2537:3: note: 'ToString' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:62:65: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        ContextifyContext* ctx = new ContextifyContext(info[0]->ToObject());
                                                                ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:77:39: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<String> code = info[0]->ToString();
                                      ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:83:42: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
            ScriptOrigin origin(info[1]->ToString());
                                         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:131:56: error: no matching member function for call to 'NewInstance'
        Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:4102:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:4099:44: note: candidate function not viable: requires 3 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/contextify.cc:150:16: error: no member named 'SetAccessCheckCallbacks' in 'v8::ObjectTemplate'
        otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
        ~~~~~  ^
../src/contextify.cc:176:43: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:182:80: error: too few arguments to function call, expected 2, have 1
        Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:3668:3: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:192:43: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:203:43: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:209:67: error: too few arguments to function call, expected 2, have 1
        if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:3668:3: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:210:71: error: too few arguments to function call, expected 2, have 1
            !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:3668:3: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
  ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/contextify.cc:218:43: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:229:43: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<Object> data = info.Data()->ToObject();
                                          ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:286:39: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
        Local<String> code = info[0]->ToString();
                                      ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:291:43: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
                               ? info[1]->ToString()
                                          ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:319:53: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        if (!ContextifyContext::InstanceOf(info[0]->ToObject()))
                                                    ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/contextify.cc:322:86: warning: 'ToObject' is deprecated: Use maybe version [-Wdeprecated-declarations]
        ContextifyContext* ctx = Nan::ObjectWrap::Unwrap<ContextifyContext>(info[0]->ToObject());
                                                                                     ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8.h:2549:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/eddielong/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
13 warnings and 5 errors generated.
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/11.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Code/developer-site/node_modules/contextify
gyp ERR! node -v v11.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN dev-site-scrap@1.0.0 No description
npm WARN dev-site-scrap@1.0.0 No repository field.
```

**Comment by eddielong** [comment]
Workaround for now is to downgrade to node 6:

```
brew install node@6
brew link --overwrite --force node@8
echo 'export PATH="/usr/local/opt/node@6/bin:$PATH"' >> ~/.zshrc
```

**Comment by evangoer** [comment]
Hi Eddie -- thanks for reporting this. I'm not currently maintaining this project. You are more than welcome to fork and update the deps!
